### ISSUE TITLE
tracetool.py not working in python 3.10

### ISSUE THREAD

**Issue by raelb** [capslock66/Tracetool#21]
Hi,

Since installing 3.10, For simple app:

    from tracetool import ttrace
    ttrace.debug.send ("hello world")

I get error:
![image](https://user-images.githubusercontent.com/13108198/170244078-4eb632e3-e709-4455-af54-9c632c6d0b4c.png)

Reference:
https://stackoverflow.com/questions/65499013/importerror-cannot-import-name-clock-from-time-unknown-location

**Comment by capslock66** [comment]
Hello.
I will upload a new version

To fix it now:
On tratetool.py
On method uuid(), line 2914, update this line
return str(uid) + **str(clock()) +** str(random.randrange(0, 9999))
to
return str(uid) + str(random.randrange(0, 9999))

remove line 23 : 
**from time import clock #, sleep**

**Comment by capslock66** [comment]
fixed with version 12.5

**Comment by raelb** [comment]
Thanks
