### ISSUE TITLE
Feature request: Ability to insert a comment in the viewer

### ISSUE THREAD

**Issue by raelb** [capslock66/Tracetool#23]
Hi,
It would be useful for me to be able to insert a comment trace in the viewer directly, so as to demarcate various sections in the trace.

e.g:
...
..
...
---- now I do this -----
.....
...
...
---- then I did this -----
...
...
etc..

Such traces should be able to set a color.
Usually one is doing this via code, but in some cases you want to do this manually in the viewer..

Thanks.

**Comment by raelb** [comment]
which delphi version are you using to build the viewer?

**Comment by capslock66** [comment]
> Hi, It would be useful for me to be able to insert a comment trace in the viewer directly, so as to demarcate various sections in the trace.
> 
> e.g: ... .. ... ---- now I do this ----- ..... ... ... ---- then I did this ----- ... ... etc..
> 
> Such traces should be able to set a color. Usually one is doing this via code, but in some cases you want to do this manually in the viewer..
> 
> Thanks.



> which delphi version are you using to build the viewer?

I use the free version 10.4
Compiling the viewer is not easy. A lot of packages must be installed
See the Readme xe.docx for the configuration procedure.
I hope it's up to date.

I just uploaded a new version of tracetool (13.2 build 563)
whith a new "add line" button.
Work for traces, but also the output debug string, event log  and Tail
