### ISSUE TITLE
Performance improvements to Viewer

### ISSUE THREAD

**Issue by raelb** [capslock66/Tracetool#24]
Hi, I find TraceTool viewer is quite slow when sending traces with large content, e.g. in Comment or as StrList. The slowness comes from displaying in TreeView. Display is a lot faster if content is displayed in SynEdit.

Attached is mods I made to source code:
[Viewer source.zip](https://github.com/capslock66/Tracetool/files/10871992/Viewer.source.zip)

Here is compiled version.
[Viewer x64.zip](https://github.com/capslock66/Tracetool/files/10871996/Viewer.x64.zip)

This version also handles JSON content, which is now pretty standard, and includes a JSON Viewer. If you try exe, you'll see it works nicely. (Part of my source is using TTextEditor, however this could be replaced by SynEdit, if you want)

Here is stress test app:
[Tracetool Stress Test.zip](https://github.com/capslock66/Tracetool/files/10872005/Tracetool.Stress.Test.zip)

Compiled stress test app:
[TracetoolStressTest.zip](https://github.com/capslock66/Tracetool/files/10872008/TracetoolStressTest.zip)

**Comment by capslock66** [comment]
Hi,
Effectively there is a performance issue when displaying a node with large data.
Json is now more important than Xml.
I will check your source code as soon as possible.
Thanks you for your help

**Comment by raelb** [comment]
> Effectively there is a performance issue when displaying a node with large data.

Yes. Part of what I do is, if Comment contains large data, then I truncate display in main tree, and display in SynEdit in the viewer. This makes performance very good.

**Comment by raelb** [comment]
My thought is to not add a SendJSON method. The viewer should handle json automatically, since json is so widely used...

**Comment by raelb** [comment]
It is not a problem. I can try to make a pull request on github so it will be easy for you to see the changes. I'm not sure should I make changes to the master branch or to the develop branch?

**Comment by capslock66** [comment]
No don´t worry.
I will take time to get some of your changes and apply on the differents parts of the viewer.

**Comment by raelb** [comment]
Here is the original source that I made my mods from. It should be easier for you to see the mods if you compare to that.
[Viewer source.zip](https://github.com/capslock66/Tracetool/files/10914469/Viewer.source.zip)

Anyway, the changes are mainly in `unt_TraceWin` and `unt_Details_xml.pas`

Here is a diff for `unt_TraceWin`
[unt_TraceWin diff.zip](https://github.com/capslock66/Tracetool/files/10914514/unt_TraceWin.diff.zip)

It really isn't much. Just using the xml viewer for comments/stringlist instead of vst, and truncating CellText string in main vst. :)

**Comment by capslock66** [comment]
Hello Rael.
I can't build the viewer since there is too much component I didn't installed:
TTextEditor (found in github), TStrHolder and TFormStorage (RxLib), TRzTabSheet (raise comp)
note that on all sources (pas and dfm) , CRLF was replaced by a single CR

So I started directly the viewer and the stress tool.
There is a lot of interesting stuff, like the limit to 400 chars, the "Full View" button (very interesting).
I can't take it as is, because only the "comment column" is handled.
I need to do it on the 2 columns, but also on each members send by SendObject(), sendTable() ... methodsSo probably a master detail of what the user select in the info pane.
There is also breaking changes, like how tables are displayed
I made a lot of screenshots to keep all your work.This will take some times !

**Comment by raelb** [comment]
I made some changes to JSONViewerFrame/Form, to remove dependency on RxLib and RzComp. You only need to install TTextEditor. You could replace with SynEdit if you want, but there is some code for searching in TextEditor.

[Viewer source.zip](https://github.com/capslock66/Tracetool/files/10952149/Viewer.source.zip)

Here is another dependency that displays json in a TreeView:

[27788_delphi_json_viewer_and_json_vcl_components.ZIP](https://github.com/capslock66/Tracetool/files/10952150/27788_delphi_json_viewer_and_json_vcl_components.ZIP)

Not sure why CRLF is replaced with CR. Maybe it is a github issue.

>I can't take it as is, because only the "comment column" is handled.
> I need to do it on the 2 columns, but also on each members send by SendObject(), sendTable() ... 

For me the most common use case is a trace with a label, and then data load, so only handling comment column is sufficient for me , for most of the time.

Not sure why you need to handle all cases (i.e. use the existing implementation in other cases), but anyway, I'll leave it to you.

**Comment by capslock66** [comment]
Done.
Develop merged to master
